import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Drawer, Empty, Fields, Json, Pager, ReadState, SourceLink, Status, filter, navigate, query, text, useRead, when, type Item, type Listing } from "./shared";

export function Calls({ id, refresh, onRun }: { id: string; refresh: number; onRun: (id: string) => void }) {
  const view = filter("view", "calls"), run = filter("run_id"), resource = filter("resource_id"), status = filter("status"), origin = filter("origin"), cursor = filter("cursor");
  const listing = useRead<Listing>(`${view === "changes" ? "/api/resource-changes" : "/api/capability-calls"}${query({ run_id: run, resource_id: resource, status, origin, cursor, limit: 50 })}`, refresh);
  const [expanded, setExpanded] = useState<string[]>([]);
  const change = (key: string, value: string) => navigate("calls", "", { [key]: value, cursor: "" });
  const detail = listing.data?.rows.find(row => row.id === id);
  return <><div className="cap-tabs cap-subtabs" role="tablist" aria-label="记录分类">{[["calls", "调用"], ["changes", "变更"]].map(([value, label]) => <button role="tab" key={value} aria-selected={view === value} onClick={() => navigate("calls", "", { view: value, cursor: "" })}>{label}</button>)}</div><div className="cap-toolbar"><input aria-label="筛选任务 ID" placeholder="任务 ID" value={run} onChange={e => change("run_id", e.target.value)} /><input aria-label="筛选能力 ID" placeholder="能力 ID" value={resource} onChange={e => change("resource_id", e.target.value)} /><select aria-label="调用结果" value={status} onChange={e => change("status", e.target.value)}><option value="">全部结果</option>{["succeeded", "failed", "timed_out", "denied", "uncertain"].map(value => <option key={value} value={value}>{value}</option>)}</select><select aria-label="调用来源" value={origin} onChange={e => change("origin", e.target.value)}><option value="">全部调用</option><option value="diagnostic">诊断</option><option value="business">业务</option></select></div><ReadState {...listing} />
    {listing.data && <p className="cap-sample">本页样本 {listing.data.rows.length}；时间窗 {listing.data.rows.length ? `${when(listing.data.rows.at(-1)?.started_at || listing.data.rows.at(-1)?.at)} 至 ${when(listing.data.rows[0].started_at || listing.data.rows[0].at)}` : "未记录"}</p>}
    <table className="cap-table"><thead><tr><th>{view === "changes" ? "资源 / 变更" : "能力 / 时间"}</th><th className="cap-secondary">{view === "changes" ? "入口 / 操作者" : "主任务 / 阶段"}</th><th>{view === "changes" ? "版本" : "结果"}</th><th className="cap-secondary">{view === "changes" ? "原因" : "排队 / 执行 / 重试"}</th></tr></thead><tbody>{listing.data?.rows.filter(row => !row.parent_call_id || expanded.includes(row.parent_call_id)).map(row => <tr key={row.id} className={row.parent_call_id ? "cap-child-call" : ""}><td><button className="cap-row-link" onClick={() => navigate("calls", row.id!)}>{text(row.resource_name || row.resource_id)}</button><small>{when(row.started_at || row.at || row.created_at)}</small>{listing.data?.rows.some(child => child.parent_call_id === row.id) && <button className="text-button" aria-expanded={expanded.includes(row.id!)} onClick={() => setExpanded(prev => prev.includes(row.id!) ? prev.filter(value => value !== row.id) : [...prev, row.id!])}><ChevronDown size={14} />子调用</button>}</td><td className="cap-secondary">{view === "changes" ? text(row.origin || row.entrypoint) : <><button className="text-button" onClick={() => row.run_id && onRun(row.run_id)}>{text(row.run_id)}</button><small>{text(row.stage)}</small></>}</td><td>{view === "changes" ? `${text(row.before_revision || row.from_version)} → ${text(row.revision || row.to_version)}` : <Status value={row.status} />}</td><td className="cap-secondary">{view === "changes" ? text(row.reason) : `${text(row.queue_ms)} ms / ${text(row.execution_ms)} ms / ${text(row.retries)}`}</td></tr>)}</tbody></table>{listing.data && !listing.data.rows.length && <Empty>{view === "changes" ? "暂无变更记录" : "未记录调用"}</Empty>}<Pager next={listing.data?.next_cursor} cursor={cursor} onChange={value => navigate("calls", "", { cursor: value })} />
    {id && <Drawer title={view === "changes" ? "变更详情" : "调用详情"} onClose={() => navigate("calls")}><ReadState {...listing} />{detail ? view === "changes" ? <><Fields values={[["资源", detail.resource_id], ["操作者", detail.actor], ["入口", detail.origin || detail.entrypoint], ["时间", when(detail.at || detail.created_at)], ["退役 / 修改原因", detail.reason]]} /><h3>版本差异</h3><Json value={detail.diff || { before: detail.before, after: detail.after }} /></> : <CallDetail row={detail} onRun={onRun} /> : listing.data && <Empty>本页未记录此调用；请按任务或能力筛选</Empty>}</Drawer>}
  </>;
}
function CallDetail({ row, onRun }: { row: Item; onRun: (id: string) => void }) {
  return <><Status value={row.status} /><Fields values={[["调用 ID", row.id], ["实际能力", row.resource_name || row.resource_id], ["版本", row.version], ["阶段", row.stage], ["来源", row.origin], ["开始时间", when(row.started_at)], ["排队（ms）", row.queue_ms], ["连接（ms）", row.connection_ms], ["执行（ms）", row.execution_ms], ["总墙钟（ms）", row.wall_ms], ["重试次数", row.retries], ["父调用", row.parent_call_id], ["实际模型", row.model], ["实际 profile", row.profile], ["技能引用", row.skill_refs || row.skills], ["记忆引用", row.memory_refs || row.memory]]} />{row.run_id && <button className="text-button" onClick={() => onRun(row.run_id)}>查看任务 {row.run_id}</button>}<h3>输入摘要</h3><Json value={row.input_summary} /><h3>结果摘要</h3><Json value={row.result_summary} /><h3>证据与产物</h3>{row.evidence_refs?.map((reference: string | Item, i: number) => <p key={i}><SourceLink value={typeof reference === "string" ? reference : reference.url || reference.href} /></p>)}{row.error && <><h3>错误</h3><Json value={row.error} /></>}<details><summary>原始日志</summary><Json value={row.logs || row.raw_log} /></details></>;
}
