import { useEffect, useState } from "react";
import { FileSearch, Plus, RefreshCw, Save, Search, Settings2, Trash2 } from "lucide-react";
import { api } from "../api";
import { CopyId, Drawer, Empty, ErrorLine, Fields, Json, Modes, Operation, Pager, ReadState, SourceLink, Status, Switch, encoded, filter, navigate, query, text, useOperation, useRead, when, type Item, type Listing } from "./shared";

const views = [["preferences", "长期偏好"], ["documents", "资料库"], ["context", "对话上下文"], ["checkpoints", "任务断点"]];
export function Memory({ id, refresh, conversations, runs, onRun }: { id: string; refresh: number; conversations: Item[]; runs: Item[]; onRun: (id: string) => void }) {
  const view = filter("view", "preferences");
  return <><div className="cap-tabs cap-subtabs" role="tablist" aria-label="记忆分类">{views.map(([value, label]) => <button role="tab" key={value} aria-selected={view === value} onClick={() => navigate("memory", "", { view: value })}>{label}</button>)}</div>
    {view === "preferences" && <Preferences id={id} refresh={refresh} />}{view === "documents" && <Documents id={id} refresh={refresh} />}{view === "context" && <Context refresh={refresh} conversations={conversations} />}{view === "checkpoints" && <Checkpoints id={id} refresh={refresh} runs={runs} conversations={conversations} onRun={onRun} />}
  </>;
}

function Preferences({ id, refresh }: { id: string; refresh: number }) {
  const [revision, setRevision] = useState(0), [error, setError] = useState<unknown>(), [busy, setBusy] = useState(false);
  const q = filter("query"), scope = filter("scope"), cursor = filter("cursor");
  const listing = useRead<Listing>(`/api/memory/items${query({ query: q, scope, cursor, limit: 50 })}`, refresh + revision);
  const row = listing.data?.rows.find(item => item.id === id);
  return <><div className="cap-toolbar"><input aria-label="搜索偏好" placeholder="搜索偏好" value={q} onChange={e => navigate("memory", "", { query: e.target.value, cursor: "" })} /><select aria-label="偏好作用域" value={scope} onChange={e => navigate("memory", "", { scope: e.target.value, cursor: "" })}><option value="">全部作用域</option>{["workspace", "account", "column", "conversation"].map(value => <option key={value} value={value}>{scopeName(value)}</option>)}</select><button className="quiet-button" onClick={() => navigate("memory", "new")}><Plus size={16} />添加偏好</button></div>
    <ReadState {...listing} /><ErrorLine error={error} retry={listing.reload} /><table className="cap-table"><thead><tr><th>内容</th><th className="cap-secondary">作用域 / 来源</th><th>状态</th><th className="cap-secondary">有效期 / 最近使用</th></tr></thead><tbody>{listing.data?.rows.map(item => <tr key={item.id}><td><button className="cap-row-link" onClick={() => navigate("memory", item.id!)}>{text(item.content)}</button></td><td className="cap-secondary">{scopeName(item.scope)}<small><SourceLink value={item.source_ref} /></small></td><td><Switch label={`启用偏好${item.key || item.id}`} value={!!item.active} disabled={busy} onChange={async () => { setBusy(true); setError(undefined); try { await api(`/api/memory/items/${encoded(item.id!)}`, "PATCH", { expected_revision: item.revision, active: !item.active, reason: "管理页调整启用状态" }); setRevision(v => v + 1); } catch (e) { setError(e); } finally { setBusy(false); } }} /></td><td className="cap-secondary">{item.expires_at ? when(item.expires_at) : "长期"}<small>{item.last_used_at ? when(item.last_used_at) : "未记录使用"}</small></td></tr>)}</tbody></table>{listing.data && !listing.data.rows.length && <Empty>暂无长期偏好</Empty>}
    <Pager next={listing.data?.next_cursor} cursor={cursor} onChange={value => navigate("memory", "", { cursor: value })} />
    {(id === "new" || row) && <PreferenceForm key={id} row={row} onChanged={() => { setRevision(v => v + 1); navigate("memory", "", undefined, false, true); }} />}
  </>;
}
function scopeName(value: string) { return ({ workspace: "工作空间", account: "账号", column: "栏目", conversation: "对话" } as Record<string, string>)[value] || value; }
function PreferenceForm({ row, onChanged, conversationId }: { row?: Item; onChanged: () => void; conversationId?: string }) {
  const [values, setValues] = useState({ key: row?.key || "", content: row?.content || "", scope: row?.scope || (conversationId ? "conversation" : "workspace"), scope_id: row?.scope_id || conversationId || "", expires_at: row?.expires_at || "", reason: "", source_ref: row?.source_ref || "" });
  const [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>();
  const operation = useOperation(onChanged);
  const set = (key: keyof typeof values, value: string) => { setValues(prev => ({ ...prev, [key]: value })); setDirty(true); };
  return <Drawer title={row ? "编辑偏好" : conversationId ? "记录纠正" : "添加偏好"} dirty={dirty} onClose={() => navigate("memory", "", conversationId ? { correction: "" } : undefined)}><ErrorLine error={error} />{row && <CopyId id={row.id!} />}
    <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(undefined); try { await api(row ? `/api/memory/items/${encoded(row.id!)}` : "/api/memory/items", row ? "PATCH" : "POST", { ...values, expires_at: values.expires_at || null, origin: row?.origin || "manual", active: row?.active ?? true, ...(row ? { expected_revision: row.revision } : {}) }); setDirty(false); onChanged(); } catch (error) { setError(error); } finally { setBusy(false); } }}>
      <label className="cap-field">偏好标识<input value={values.key} onChange={e => set("key", e.target.value)} required /></label><label className="cap-field">偏好内容<textarea rows={5} value={values.content} onChange={e => set("content", e.target.value)} required /></label><label className="cap-field">作用域<select value={values.scope} onChange={e => set("scope", e.target.value)}>{["workspace", "account", "column", "conversation"].map(value => <option key={value} value={value}>{scopeName(value)}</option>)}</select></label><label className="cap-field">关联栏目 / 对话 ID<input value={values.scope_id} onChange={e => set("scope_id", e.target.value)} required={values.scope !== "workspace"} /></label><label className="cap-field">有效期<input type="datetime-local" value={values.expires_at} onChange={e => set("expires_at", e.target.value)} /></label><label className="cap-field">来源引用<input value={values.source_ref} onChange={e => set("source_ref", e.target.value)} /></label><label className="cap-field">变更原因<textarea value={values.reason} onChange={e => set("reason", e.target.value)} required /></label>
      <p className="muted">保存后影响{scopeName(values.scope)}范围内的后续任务；不改变已冻结任务。</p><button className="primary-button" disabled={busy}><Save size={16} />保存偏好</button>
    </form>{row?.conflicts && <><h3>冲突偏好与来源</h3><Json value={row.conflicts} /></>}{row && <details><summary>忘记偏好</summary><p>使派生上下文引用失效；不删除历史稿件或图片。</p><button className="quiet-button cap-danger" disabled={!values.reason.trim()} onClick={() => operation.start(`/api/memory/items/${encoded(row.id!)}/forget`, { expected_revision: row.revision, reason: values.reason })}><Trash2 size={16} />确认忘记</button><Operation state={operation} /></details>}
  </Drawer>;
}

function Documents({ id, refresh }: { id: string; refresh: number }) {
  const [revision, setRevision] = useState(0);
  const q = filter("documentQuery"), namespace = filter("namespace"), type = filter("type"), purpose = filter("purpose"), status = filter("index_status"), cursor = filter("documentCursor");
  const listing = useRead<Listing>(`/api/knowledge/documents${query({ query: q, namespace, type, purpose, index_status: status, limit: 50, cursor })}`, refresh + revision);
  const operation = useOperation(() => setRevision(v => v + 1));
  const change = (key: string, value: string) => navigate("memory", "", { [key]: value, documentCursor: "" });
  return <><div className="cap-toolbar"><input aria-label="搜索原文" placeholder="搜索原文" value={q} onChange={e => change("documentQuery", e.target.value)} /><select aria-label="数据命名空间" value={namespace} onChange={e => change("namespace", e.target.value)}><option value="">选择命名空间</option>{listing.data?.namespaces?.map((value: string | Item) => { const name = typeof value === "string" ? value : value.name || value.namespace; return <option key={name} value={name}>{name}</option>; })}</select><input aria-label="文档类型" placeholder="类型" value={type} onChange={e => change("type", e.target.value)} /><select aria-label="文档用途" value={purpose} onChange={e => change("purpose", e.target.value)}><option value="">全部用途</option><option value="evidence">证据</option><option value="style_reference">风格参考</option><option value="duplicate_reference">历史查重</option></select><select aria-label="索引状态" value={status} onChange={e => change("index_status", e.target.value)}><option value="">全部索引状态</option>{["ready", "pending", "failed", "skipped_empty"].map(value => <option key={value} value={value}>{value}</option>)}</select>
    <button className="quiet-button" onClick={() => navigate("memory", "search")}><Search size={16} />测试检索</button><button className="quiet-button" disabled={!namespace} onClick={() => operation.start("/api/knowledge/index-jobs", { namespace })}><RefreshCw size={16} />增量索引</button></div>
    <ReadState {...listing} /><Operation state={operation} />{listing.data?.index_progress && <Fields values={[["索引进度", listing.data.index_progress]]} />}<table className="cap-table"><thead><tr><th>标题</th><th className="cap-secondary">来源 / 类型 / 原文日期</th><th className="cap-secondary">用途</th><th>索引状态</th><th className="cap-secondary">更新于</th></tr></thead><tbody>{listing.data?.rows.map(row => <tr key={`${row.namespace}:${row.id}`}><td><button className="cap-row-link" onClick={() => navigate("memory", row.id!, { namespace: row.namespace || namespace })}>{text(row.title || row.name || row.id)}</button></td><td className="cap-secondary">{text(row.source || row.type)}<small>{when(row.published_at)}</small></td><td className="cap-secondary">{text(row.purposes || row.purpose)}</td><td><Status value={row.index_status} /></td><td className="cap-secondary">{when(row.updated_at)}</td></tr>)}</tbody></table>{listing.data && !listing.data.rows.length && <Empty>没有匹配的文档</Empty>}<Pager next={listing.data?.next_cursor} cursor={cursor} onChange={value => navigate("memory", "", { documentCursor: value })} />
    {id === "search" ? <KnowledgeSearch namespace={namespace} /> : id && <DocumentDetail key={`${namespace}:${id}`} id={id} namespace={namespace} refresh={refresh + revision} onChanged={() => setRevision(v => v + 1)} />}
  </>;
}
function KnowledgeSearch({ namespace }: { namespace: string }) {
  const [q, setQ] = useState(""), [ns, setNs] = useState(namespace), [purpose, setPurpose] = useState("evidence"), [result, setResult] = useState<Item | null>(null), [error, setError] = useState<unknown>(), [busy, setBusy] = useState(false);
  return <Drawer title="测试检索" onClose={() => navigate("memory")}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(undefined); setResult(null); try { setResult(await api<Item>("/api/knowledge/search", "POST", { query: q, namespace: ns, purpose, limit: 10 })); } catch (e) { setError(e); } finally { setBusy(false); } }}><label className="cap-field">查询词<input value={q} onChange={e => setQ(e.target.value)} required /></label><label className="cap-field">检索命名空间<input value={ns} onChange={e => setNs(e.target.value)} required /></label><label className="cap-field">检索用途<select value={purpose} onChange={e => setPurpose(e.target.value)}><option value="evidence">证据</option><option value="style_reference">风格参考</option><option value="duplicate_reference">历史查重</option></select></label><button className="primary-button" disabled={busy}><Search size={16} />执行检索</button></form><ErrorLine error={error} />{result && <><Fields values={[["耗时（ms）", result.elapsed_ms], ["排序方式", result.ranking], ["嵌入模型", result.embedding_model], ["向量维度", result.embedding_dimensions]]} />{result.rows?.length ? result.rows.map((row: Item, i: number) => <section className="cap-band" key={row.id || i}><button className="cap-row-link" onClick={() => navigate("memory", row.document_id || row.id!, { namespace: ns })}>{text(row.title)}</button><p>{text(row.content || row.text || row.snippet)}</p><Fields values={[["匹配原因", row.match_reason || row.reason], ["检索排序分数", row.score]]} /></section>) : <Empty>无匹配结果</Empty>}</>}</Drawer>;
}
function DocumentDetail({ id, namespace, refresh, onChanged }: { id: string; namespace: string; refresh: number; onChanged: () => void }) {
  const detail = useRead<Item>(`/api/knowledge/documents/${encoded(id)}${query({ namespace })}`, refresh);
  const [excluded, setExcluded] = useState<string[]>([]), [annotation, setAnnotation] = useState(""), [source, setSource] = useState(""), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<unknown>();
  useEffect(() => { if (detail.data && !dirty) { setExcluded(detail.data.policy?.excluded_purposes || []); setAnnotation(detail.data.policy?.annotation || ""); setSource(detail.data.policy?.source_ref || ""); } }, [detail.data, dirty]);
  return <Drawer title={detail.data?.title || "文档详情"} dirty={dirty} onClose={() => navigate("memory")}><ReadState {...detail} /><ErrorLine error={error} retry={detail.reload} />{detail.data && <><CopyId id={id} /><SourceLink value={detail.data.source_url || detail.data.url} /><Fields values={[["命名空间", namespace || detail.data.namespace], ["采集时间", when(detail.data.collected_at)], ["原文日期", when(detail.data.published_at)]]} /><h3>来源原文</h3><pre className="cap-original">{text(detail.data.body || detail.data.content || detail.data.text)}</pre><h3>纠错注释</h3><label className="cap-field">注释<textarea value={annotation} onChange={e => { setAnnotation(e.target.value); setDirty(true); }} /></label><label className="cap-field">纠错来源引用<input value={source} onChange={e => { setSource(e.target.value); setDirty(true); }} /></label><h3>排除检索用途</h3>{[["evidence", "证据"], ["style_reference", "风格参考"], ["duplicate_reference", "历史查重"]].map(([value, label]) => <label className="cap-checkbox" key={value}><input type="checkbox" checked={excluded.includes(value)} onChange={e => { setExcluded(prev => e.target.checked ? [...prev, value] : prev.filter(v => v !== value)); setDirty(true); }} />{label}</label>)}<button className="primary-button" disabled={busy || !dirty} onClick={async () => { setBusy(true); setError(undefined); try { await api(`/api/knowledge/documents/${encoded(id)}/policy`, "PATCH", { namespace: namespace || detail.data?.namespace, expected_revision: detail.data?.policy?.revision ?? detail.data?.revision, excluded_purposes: excluded, annotation, source_ref: source }); setDirty(false); onChanged(); } catch (e) { setError(e); } finally { setBusy(false); } }}><Save size={16} />保存用途与注释</button><details><summary>索引片段</summary><Json value={detail.data.chunks} /></details><details><summary>修订历史</summary><Json value={detail.data.versions} /></details></>}</Drawer>;
}

function Context({ refresh, conversations }: { refresh: number; conversations: Item[] }) {
  const cid = filter("conversation"), [revision, setRevision] = useState(0), [policyOpen, setPolicyOpen] = useState(false);
  const detail = useRead<Item>(cid ? `/api/conversations/${encoded(cid)}/context` : "", refresh + revision);
  const operation = useOperation(() => setRevision(v => v + 1));
  return <><div className="cap-toolbar"><select aria-label="上下文对话" value={cid} onChange={e => navigate("memory", "", { conversation: e.target.value, correction: "" })}><option value="">选择对话</option>{conversations.map(row => <option key={row.id} value={row.id}>{row.title || row.id}</option>)}</select><button className="quiet-button" disabled={!detail.data} onClick={() => setPolicyOpen(true)}><Settings2 size={16} />上下文策略</button><button className="quiet-button" disabled={!detail.data || ["running", "pending"].includes(operation.operation?.status)} onClick={() => operation.start(`/api/conversations/${encoded(cid)}/compact`, {})}><FileSearch size={16} />生成压缩摘要</button><button className="quiet-button" disabled={!cid} onClick={() => navigate("memory", "", { correction: "1" })}><Plus size={16} />记录纠正</button></div><ReadState {...detail} /><Operation state={operation} />
    {!cid && <Empty>选择一个对话查看上下文</Empty>}{detail.data && <><Status value={detail.data.status} /><Fields values={[["压缩主控模型", detail.data.model], ["原始消息数", detail.data.raw_message_count], ["token 估算", detail.data.tokens_estimate], ["当前策略", detail.data.policy]]} /><div className="cap-context-columns"><section><h3>摘要与约束来源</h3><Json value={detail.data.context} /></section><section><h3>覆盖范围与保留消息</h3><Json value={detail.data.context?.coverage || detail.data.context?.retained_messages || detail.data.coverage} /></section></div><details><summary>查看本次实际上下文</summary>{detail.data.actual_usage ? <Json value={detail.data.actual_usage} /> : <Empty>尚未用于生成 / 未记录实际发送范围</Empty>}</details><h3>历史压缩版本</h3><Json value={detail.data.snapshots} /></>}
    {policyOpen && detail.data && <ContextPolicy key={cid} cid={cid} row={detail.data} onClose={() => setPolicyOpen(false)} onChanged={() => { setRevision(v => v + 1); setPolicyOpen(false); }} />}
    {filter("correction") && cid && <PreferenceForm conversationId={cid} onChanged={() => { setRevision(v => v + 1); navigate("memory", "", { correction: "" }, false, true); }} />}
  </>;
}
function ContextPolicy({ cid, row, onClose, onChanged }: { cid: string; row: Item; onClose: () => void; onChanged: () => void }) {
  const [mode, setMode] = useState(row.policy?.mode || "manual"), [threshold, setThreshold] = useState(row.policy?.soft_threshold ?? 12000), [keep, setKeep] = useState(row.policy?.keep_recent ?? 16), [dirty, setDirty] = useState(false), [error, setError] = useState<unknown>(), [busy, setBusy] = useState(false);
  return <Drawer title="上下文策略" dirty={dirty} onClose={onClose}><Modes modes={["auto", "manual"]} value={mode} onChange={value => { setMode(value); setDirty(true); }} /><label className="cap-field">压缩阈值（tokens）<input type="number" min="256" max="200000" value={threshold} onChange={e => { setThreshold(Number(e.target.value)); setDirty(true); }} /></label><label className="cap-field">近期保留消息数<input type="number" min="1" max="1000" value={keep} onChange={e => { setKeep(Number(e.target.value)); setDirty(true); }} /></label><ErrorLine error={error} /><button className="primary-button" disabled={busy || !dirty} onClick={async () => { setBusy(true); setError(undefined); try { await api(`/api/conversations/${encoded(cid)}/context-policy`, "PUT", { expected_revision: row.policy_revision, mode, soft_threshold: threshold, keep_recent: keep }); setDirty(false); onChanged(); } catch (e) { setError(e); } finally { setBusy(false); } }}><Save size={16} />保存上下文策略</button></Drawer>;
}
function Checkpoints({ id, refresh, runs, conversations, onRun }: { id: string; refresh: number; runs: Item[]; conversations: Item[]; onRun: (id: string) => void }) {
  const row = runs.find(run => run.id === id), capability = useRead<Item>(id ? `/api/runs/${encoded(id)}/capabilities` : "", refresh);
  const [busy, setBusy] = useState(false), [error, setError] = useState<unknown>();
  return <><table className="cap-table"><thead><tr><th>任务</th><th>状态</th><th className="cap-secondary">断点</th></tr></thead><tbody>{runs.map(run => <tr key={run.id}><td><button className="cap-row-link" onClick={() => navigate("memory", run.id!)}>{run.title || run.id}</button></td><td>{text(run.status_label || run.status)}</td><td className="cap-secondary">{text(run.stage || run.activity?.stage)}</td></tr>)}</tbody></table>{!runs.length && <Empty>暂无任务断点</Empty>}{id && <Drawer title={row?.title || "任务断点"} onClose={() => navigate("memory")}><ReadState {...capability} /><ErrorLine error={error} />{capability.data?.status === "not_recorded" || capability.data?.not_recorded ? <Empty>该版本未采集</Empty> : <><Fields values={[["目标数量", row?.activity?.requested], ["已生成", row?.activity?.counts?.generated], ["已审核", row?.activity?.counts?.reviewed], ["已保存草稿", row?.activity?.counts?.saved], ["待继续步骤", row?.stage], ["冻结版本", capability.data?.version]]} /><Json value={capability.data} /></>}
      <div className="cap-actions"><button className="quiet-button" onClick={() => onRun(id)}>查看运行记录</button>{row && ["failed", "interrupted", "partial", "needs_resume"].includes(row.status) && <button className="primary-button" disabled={busy || !conversations.some(c => c.runs?.includes(id))} onClick={async () => { const conversation = conversations.find(c => c.runs?.includes(id)); if (!conversation) return; setBusy(true); setError(undefined); try { const resumed = await api<Item>(`/api/runs/${encoded(id)}/resume`, "POST", { conversation_id: conversation.id }, crypto.randomUUID()); onRun(resumed.id!); } catch (e) { setError(e); } finally { setBusy(false); } }}>确认继续任务</button>}</div>
    </Drawer>}</>;
}
